require("user.options")
require("user.autocmd")
require("user.wsl-clipboard")
require("user.keymaps")
require("user.plugins")
require("user.globals")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.dap")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.persisted")
require("user.lualine")
require("user.tabline")
require("user.mundo")
require("user.harpoon")

-- NOTE: make sure the order { nvim-tree, persisted, lualine, tabline-framework } to work together
