 require "user.options"
 require "user.wsl-clipboard"
 require "user.keymaps"
 require "user.plugins"
 require "user.colorscheme"
 require "user.cmp"
 require "user.lsp"
 require "user.telescope"
 require "user.treesitter"
 require "user.autopairs"
 require "user.comment"
 require "user.gitsigns"
 require "user.persisted"
 require "user.nvim-tree"
 require "user.lualine"
 require "user.tabline-framework"
 require "user.mundo"

-- NOTE: make sure the order { persisted, nvim-tree, lualine, tabline-framework } to work together
